[package]
name = "nostro2"
version = "0.1.14"
edition = "2021"
license = "MIT"
description = "Nostro2 is a simple toolset for interacting with the Nostr protocol."
repository = "https://github.com/42Pupusas/NostrO2.git"
readme = "README.md"
homepage = "https://github.com/42Pupusas/NostrO2.git"
documentation = "https://docs.rs/nostro2/latest/nostro2/"

[dependencies]
futures-util = "0.3.28"
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = { version = "0.27.0", features = ["global-context"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
hkdf = "0.12.4"
chacha20 = "0.9.1"
hmac = "0.12.1"
base64 = "0.21.5"


anyhow = "1.0.81"
tokio = { version = "1.36.0", features = ["test-util", "macros"] }
tungstenite = { version = "0.21.0", features = ["rustls-tls-webpki-roots"] }
getrandom = { version = "0.2", features = ["js"] }
url = "2.5.0"
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
rustls-pki-types = { version = "1.4.0", features = ["web"] }


