[package]
name = "nostro2"
version = "0.1.27"
edition = "2021"
license = "MIT"
description = "Nostro2 is a simple toolset for interacting with the Nostr protocol."
repository = "https://github.com/42Pupusas/NostrO2.git"
readme = "README.md"
homepage = "https://github.com/42Pupusas/NostrO2.git"
documentation = "https://docs.rs/nostro2/latest/nostro2/"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

base64 = "0.21.5"
chacha20 = "0.9.1"
hkdf = "0.12.4"
hex = "0.4.3"
hmac = "0.12.1"
rand = "0.8.5"
secp256k1 = { version = "0.27.0", features = ["global-context"] }
sha2 = "0.10.8"

url = "2.5.0"
futures-util = { version = "0.3.28", features = ["sink", "std"] }
bech32 = "0.11.0"
bip39 = { version = "2.0.0", features = ["spanish"] }
cbc = { version = "0.1.2", features = ["alloc"] }
aes = "0.8.4"
libaes = "0.7.0"
async-channel = "2.3.1"
anyhow = "1.0.89"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.36.0", features = ["test-util", "macros", "net"] }
tokio-tungstenite = { version = "0.21.0", features = ["rustls-tls-webpki-roots"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }
tokio = { version = "1.36.0", features = ["sync"] }
tokio-tungstenite-wasm = { version = "0.3.1", features = ["rustls-tls-webpki-roots"] }
rustls-pki-types = { version = "1.4.0", features = ["web"] }
wasm-bindgen-test = "0.3.42"
wasm-bindgen-futures = "0.4.42"
wasm-bindgen = "= 0.2.93"
web-time = "1.1.0"
