[workspace]
resolver="2"

members = [
    "nips",
    "nostro2",
    "nostro2-relay",
    "nostro2-web-relay",
    "nostro2-signer",
    "nostro2-web-signer", 
]

[workspace.dependencies]
# JSON
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"

nostro2-nips = { path = "nips", version = "0.1.1" }
nostro2 = { path = "nostro2", version = "0.3" }
nostro2-signer = { path = "nostro2-signer", version = "0.1.4" }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Cryptography 
base64 = "0.22"
cbc = { version = "0.1", features = ["alloc"] }
chacha20 = "0.9"
hex = "0.4.3"
hkdf = "0.12"
hmac = "0.12"
libaes = "0.7"
secp256k1 = { version = "0.30.0", features = ["rand", "std", "alloc"] }
sha2 = "0.10.8"
zeroize = "1.8.1"

# Key helpers
bech32 = "0.11"
bip39 = { version = "2.1", features = ["spanish"] }

# Miscellanea utility
futures-util = { version = "0.3", features = ["sink", "std"] }
chrono = "0.4"
tracing-test = "0.2"

# Native platform TCP
tokio = { version = "^1.43.1" }
tokio-tungstenite = { version = "0.26", features = ["rustls-tls-native-roots"] }
rustls = { version = "0.23", features = ["ring", "std", "tls12"], default-features = false }

ring = "^0.17.12" 
tokio-tungstenite-wasm = { version = "0.4.0", features = ["rustls-tls-webpki-roots"] }
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3" }

