[package]
name = "nostro2"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "Nostro2 is a simple toolset for interacting with the Nostr protocol."
repository = "https://github.com/42Pupusas/NostrO2.git"
readme = "README.md"
homepage = "https://github.com/42Pupusas/NostrO2.git"
documentation = "https://docs.rs/nostro2/latest/nostro2/"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
tokio-tungstenite = {version = "0.18.0", features = ["native-tls"]}
serde_json = "1.0"
url = "2.3.1"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
secp256k1 = {version="0.27.0", features=["global-context"]}
sha2 = "0.10.6"
hex = "0.4.3"
base64 = "0.21.0"
native-tls = "0.2.11"
httparse = "1.8.0"
http = "0.2.9"
sha1 = "0.10.5"
getrandom = { version = "0.2", default-features = false, features = ["js"] }
tungstenite = "0.19.0"
tokio-test = "0.4.2"
